// frontend/src/App.jsx
import './App.css';
import {Routes, Route, Navigate} from "react-router-dom";
import Home from './components/home/Home';
import Header from './components/header/Header';
import MoviePage from './components/moviepage/MoviePage';
import Browse from './components/browse/Browse';
import { createTheme, ThemeProvider } from '@mui/material';
import SidePanel from './components/browse/SidePanel/SidePanel';

function App() {

  const theme = createTheme({
    palette: {
      mode: "dark"
    }
  });

  return (
      <div className="App">
        <ThemeProvider theme={theme}>
          <Header/>
          <Routes>
            <Route path="" element={<Navigate replace to="home"/>}/>
            <Route path="home" element={<Home />} />
            <Route path="movie/:id" element={<MoviePage />} />
            <Route path="browse/" element={<Browse />} />
          </Routes>
        </ThemeProvider>
      </div>
  );
}

export default App;

// solid-frontend/src/App.tsx
import type { Component } from 'solid-js'
import { lazy } from 'solid-js'
import { Router, Routes, Route } from '@solidjs/router'

import NavBar from './components/navbar/NavBar'
import Home from './routes/Home'

const Search = lazy(() => import('./routes/Search'))

import './App.css'

const App: Component = () =>
  (
    <Router>
      <NavBar/>
      <Routes>
        <Route path="/" component={Home}/>
        <Route path="/search/:movie?" component={Search}/>
      </Routes>
    </Router>
  )

export default App
