// new-frontend/src/components/moviepage/MoviePage.tsx
import { Show, createResource } from "solid-js";
import "./MoviePage.css";

const queryMovie: (id: number) => Promise<Movie> = (id) =>
  fetch(`http://localhost:8080/api/movies/id/${id}`)
    .then(res => res.json())

type Genre = {
  genreID: number;
  name: string;
};

type Movie = {
  movieID: number;
  posterLink: string;
  seriesTitle: string;
  releasedYear: number;
  certificate: string;
  runtime: string;
  genre: Genre[];
  imdbRating: number;
  overview: string;
  metaScore: number;
  director: string;
  star1: string;
  star2: string;
  star3: string;
  star4: string;
  noOfVotes: number;
  gross: string;
};

export default function MoviePage() {
  const [movie] = createResource(() => queryMovie(112));

  return (
    <Show when={!movie.loading} fallback={<div>Loading...</div>}>
      <div class="movie-card">
        <div class="movie-detail">
          <div class="movie-poster-container">
            <div class="movie-poster">
              <img src={movie()?.posterLink} alt="" />
            </div>
          </div>
          <div class="movie-text-container">
            <div class="movie-title">
              <h4>{movie()?.seriesTitle}</h4>
            </div>
            <div class="movie-description">
              <p>{movie()?.overview}</p>
            </div>
            <div class="movie-description">
              <p>
                {movie()?.genre.map((x) => x.name).join(", ")}
              </p>
            </div>
            <div class="movie-description">
              <p>Cast: {[movie()?.star1, movie()?.star2, movie()?.star3, movie()?.star4].join(", ")}</p>
            </div>
            <div class="movie-rating">
              <h4>{movie()?.imdbRating} / 10</h4>
            </div>
          </div>
        </div>
      </div>
    </Show>
  );
}

// frontend/src/components/moviepage/MoviePage.jsx
import './MoviePage.css';
import React, { useState, useEffect } from 'react'
import { useParams } from 'react-router-dom';

const MoviePage = () => {

    const { id } = useParams()
    const [movie, setMovie] = useState()
    const [loading, setLoading] = useState(true)

    useEffect(() => {
        fetch("http://localhost:8080/api/movies/id/"+id)
        .then(response => response.json())
        .then(data => {
          console.log(data)
          setMovie(data)
        }).finally( () =>{
            setLoading(false)
        })
    }, [id])

    if (loading) {
        return <h1>LOADING...</h1>
    }

    return (
        <div className='movie-card'>
            <div className='movie-detail'>
                <div className='movie-poster-container'>
                    <div className='movie-poster'>
                        <img src={movie.posterLink} alt=''/>
                    </div>
                </div>
                <div className='movie-text-container'>
                    <div className='movie-title'>
                        <h3>{movie.seriesTitle}</h3>
                    </div>
                    <div className='movie-description'>
                        <p>{movie.overview}</p>
                    </div>
                    <div className='movie-description'>
                        <p>{movie.genre.map((x) => x.name).join(", ")}</p>
                    </div>
                    <div className='movie-description'>
                        <p>Starring: {movie.starring.map((x) => x.name).join(", ")}</p>
                    </div>
                    <div className='movie-rating'>
                        <h4>{movie.imdbRating} / 10</h4>
                    </div>
                </div>

            </div>
        </div>
    )
}

export default MoviePage
